# Once done, this will define
#
#  SHMIPCAPI_INCLUDE_DIR - the SHMIPCAPI include directory
#  SHMIPCAPI_LIBRARY_DIR - the SHMIPCAPI library directory
#  SHMIPCAPI_LIBS - link these to use SHMIPCAPI
#
#  ......

MACRO(LOAD_LIBSHMIPCAPI os arch)
    MESSAGE(INFO "--------------------------------")
    SET(3RDPARTY_DIR /opt/rk3568_sdk/thirdparty/shmipcapi)
    MESSAGE(STATUS "3RDPARTY_DIR: ${3RDPARTY_DIR}")
    #FIND_FILE(SPDLOG_INCLUDE_DIR include ${3RDPARTY_DIR} NO_DEFAULT_PATH)
    #FIND_FILE(SPDLOG_LIBRARY_DIR lib ${3RDPARTY_DIR} NO_DEFAULT_PATH)
    SET(SHMIPCAPI_INCLUDE_DIR ${3RDPARTY_DIR}/include)
    SET(SHMIPCAPI_LIBRARY_DIR ${3RDPARTY_DIR}/lib)

    IF (CMAKE_SYSTEM_NAME MATCHES "Linux")
        SET(SHMIPCAPI_LIBS ShmIPCSubApi ShmIPCPubApi pthread)
    ELSEIF (CMAKE_SYSTEM_NAME MATCHES "Windows")
       SET(SHMIPCAPI_LIBS spdlog)
    ENDIF (CMAKE_SYSTEM_NAME MATCHES "Linux")

    IF(SHMIPCAPI_INCLUDE_DIR)
        SET(SHMIPCAPI_LIBRARY_DIR "${SHMIPCAPI_LIBRARY_DIR}")
        MESSAGE(STATUS "SHMIPCAPI_INCLUDE_DIR : ${SHMIPCAPI_INCLUDE_DIR}")
        MESSAGE(STATUS "SHMIPCAPI_LIBRARY_DIR : ${SHMIPCAPI_LIBRARY_DIR}")
        MESSAGE(STATUS "SHMIPCAPI_LIBS : ${SPDLOG_LIBS}")
    ELSE()
        MESSAGE(FATAL_ERROR "SHMIPCAPI_LIBS not found!")
    ENDIF()
ENDMACRO()
